### ISSUE TITLE
Still have incorrect calls to random.nextInt()

### ISSUE THREAD

**Issue by starlingfire** [YeoXuHang/Geode-Plus#32]
https://github.com/YeoXuHang/Geode-Plus/blob/c08aa502acb65470f91ba8b29a54574702181bce/common/src/main/java/net/yeoxuhang/geodeplus/common/block/RedstoneOresClusterBlock.java#L155

It doesn't seem like 0 is a proper upper bound for `nextInt()`, as `nextInt` returns a number between 0 and N-1. Your approach seems like you're trying to make it choose an int between 0 and 0, which will always be 0, in which case why not remove that statement altogether? Unless I'm misunderstanding your approach of determining experience orb amounts based on bud size.

Here is the error from my server:
```
java.lang.IllegalArgumentException: Bound must be positive
	at net.minecraft.world.level.levelgen.BitRandomSource.m_188503_(BitRandomSource.java:22) ~[server-1.19.2-20220805.130853-srg.jar%23323!/:?] {re:classloading}
	at net.yeoxuhang.geodeplus.common.block.RedstoneOresClusterBlock.m_213646_(RedstoneOresClusterBlock.java:155) ~[geodeforge-1.1.5-1.19.2.jar%23193!/:?] {re:classloading}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_222967_(BlockBehaviour.java:706) ~[server-1.19.2-20220805.130853-srg.jar%23323!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:BlockStateBaseMixin,pl:mixin:APP:snowrealmagic.mixins.json:BlockStateMixin,pl:mixin:APP:canary.mixins.json:ai.pathing.BlockStateBaseMixin,pl:mixin:APP:canary.mixins.json:block.flatten_states.BlockStateBaseMixin,pl:mixin:APP:canary.mixins.json:chunk.block_counting.BlockStateBaseMixin,pl:mixin:APP:byg.mixins.json:common.block.MixinBlockBehaviourBlockStateBase,pl:mixin:APP:twigs.mixins.json:BlockStateBaseMixin,pl:mixin:APP:ferritecore.blockstatecache.mixin.json:BlockStateBaseMixin,pl:mixin:A}
	at com.simibubi.create.foundation.utility.BlockHelper.destroyBlockAs(BlockHelper.java:200) ~[create-1.19.2-0.5.0.g.jar%23142!/:0.5.0.g] {re:classloading}
	at com.simibubi.create.foundation.utility.BlockHelper.destroyBlock(BlockHelper.java:154) ~[create-1.19.2-0.5.0.g.jar%23142!/:0.5.0.g] {re:classloading}
	at com.simibubi.create.content.contraptions.components.actors.BlockBreakingMovementBehaviour.tickBreaker(BlockBreakingMovementBehaviour.java:202) ~[create-1.19.2-0.5.0.g.jar%23142!/:0.5.0.g] {re:classloading,xf:fml:openpartiesandclaims:xaero_pac_create_blockbreakingmovementbehaviour_tickbreaker}
	at com.simibubi.create.content.contraptions.components.actors.BlockBreakingMovementBehaviour.tick(BlockBreakingMovementBehaviour.java:125) ~[create-1.19.2-0.5.0.g.jar%23142!/:0.5.0.g] {re:classloading,xf:fml:openpartiesandclaims:xaero_pac_create_blockbreakingmovementbehaviour_tickbreaker}
	at com.simibubi.create.content.contraptions.components.structureMovement.AbstractContraptionEntity.tickActors(AbstractContraptionEntity.java:464) ~[create-1.19.2-0.5.0.g.jar%23142!/:0.5.0.g] {re:classloading,pl:runtimedistcleaner:A}
	at com.simibubi.create.content.contraptions.components.structureMovement.ControlledContraptionEntity.tickContraption(ControlledContraptionEntity.java:140) ~[create-1.19.2-0.5.0.g.jar%23142!/:0.5.0.g] {re:classloading,pl:runtimedistcleaner:A}
	at com.simibubi.create.content.contraptions.components.structureMovement.AbstractContraptionEntity.m_8119_(AbstractContraptionEntity.java:367) ~[create-1.19.2-0.5.0.g.jar%23142!/:0.5.0.g] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:658) ~[server-1.19.2-20220805.130853-srg.jar%23323!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_serverlevel_ispositionentityticking,xf:fml:sereneseasons:temperature_transformer,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_serverlevel_ispositionentityticking,xf:fml:sereneseasons:temperature_transformer,pl:mixin:APP:kubejs-common.mixins.json:ServerLevelMixin,pl:mixin:APP:snowrealmagic.mixins.json:ServerLevelMixin,pl:mixin:APP:leavesbegone.common.mixins.json:ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:pluto.mixins.json:server.fastchunkentityaccess.ServerWorldMixin,pl:mixin:APP:immersive_weathering-common.mixins.json:ServerLevelMixin,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:chunk.entity_class_groups.ServerLevelAccessor,pl:mixin:APP:canary.mixins.json:entity.inactive_navigations.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:profiler.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:util.entity_movement_tracking.ServerLevelAccessor,pl:mixin:APP:byg.mixins.json:common.world.MixinServerLevel,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin,pl:mixin:APP:biomemakeover-common.mixins.json:multipart.ServerLevelMixin,pl:mixin:APP:alternate-current.mixins.json:ServerLevelMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:blueprint.mixins.json:ServerLevelMixin,pl:mixin:APP:friendsandfoes-common.mixins.json:ServerWorldAccessor,pl:mixin:APP:friendsandfoes-common.mixins.json:ServerWorldMixin,pl:mixin:APP:rottencreatures-common.mixins.json:common.ServerLevelMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
	at net.minecraft.world.level.Level.m_46653_(Level.java:457) ~[server-1.19.2-20220805.130853-srg.jar%23323!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_level_destroyblock,re:computing_frames,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_level_destroyblock,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_level_destroyblock,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:sereneseasons.mixins.json:MixinLevel,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.LevelMixin,pl:mixin:APP:canary.mixins.json:world.block_entity_retrieval.LevelMixin,pl:mixin:APP:canary.mixins.json:world.block_entity_ticking.sleeping.LevelMixin,pl:mixin:APP:canary.mixins.json:world.chunk_access.LevelMixin,pl:mixin:APP:canary.mixins.json:world.inline_block_access.LevelMixin,pl:mixin:APP:canary.mixins.json:world.inline_height.LevelMixin,pl:mixin:APP:lootr.mixins.json:MixinLevel,pl:mixin:APP:citadel.mixins.json:LevelMixin,pl:mixin:APP:biomemakeover-common.mixins.json:multipart.LevelMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:323) ~[server-1.19.2-20220805.130853-srg.jar%23323!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_serverlevel_ispositionentityticking,xf:fml:sereneseasons:temperature_transformer,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_serverlevel_ispositionentityticking,xf:fml:sereneseasons:temperature_transformer,pl:mixin:APP:kubejs-common.mixins.json:ServerLevelMixin,pl:mixin:APP:snowrealmagic.mixins.json:ServerLevelMixin,pl:mixin:APP:leavesbegone.common.mixins.json:ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:pluto.mixins.json:server.fastchunkentityaccess.ServerWorldMixin,pl:mixin:APP:immersive_weathering-common.mixins.json:ServerLevelMixin,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:chunk.entity_class_groups.ServerLevelAccessor,pl:mixin:APP:canary.mixins.json:entity.inactive_navigations.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:profiler.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:util.entity_movement_tracking.ServerLevelAccessor,pl:mixin:APP:byg.mixins.json:common.world.MixinServerLevel,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin,pl:mixin:APP:biomemakeover-common.mixins.json:multipart.ServerLevelMixin,pl:mixin:APP:alternate-current.mixins.json:ServerLevelMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:blueprint.mixins.json:ServerLevelMixin,pl:mixin:APP:friendsandfoes-common.mixins.json:ServerWorldAccessor,pl:mixin:APP:friendsandfoes-common.mixins.json:ServerWorldMixin,pl:mixin:APP:rottencreatures-common.mixins.json:common.ServerLevelMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[server-1.19.2-20220805.130853-srg.jar%23323!/:?] {re:mixin,re:classloading,pl:mixin:APP:canary.mixins.json:collections.entity_ticking.EntityTickListMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:303) ~[server-1.19.2-20220805.130853-srg.jar%23323!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_serverlevel_ispositionentityticking,xf:fml:sereneseasons:temperature_transformer,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_serverlevel_ispositionentityticking,xf:fml:sereneseasons:temperature_transformer,pl:mixin:APP:kubejs-common.mixins.json:ServerLevelMixin,pl:mixin:APP:snowrealmagic.mixins.json:ServerLevelMixin,pl:mixin:APP:leavesbegone.common.mixins.json:ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:pluto.mixins.json:server.fastchunkentityaccess.ServerWorldMixin,pl:mixin:APP:immersive_weathering-common.mixins.json:ServerLevelMixin,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:chunk.entity_class_groups.ServerLevelAccessor,pl:mixin:APP:canary.mixins.json:entity.inactive_navigations.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:profiler.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:util.entity_movement_tracking.ServerLevelAccessor,pl:mixin:APP:byg.mixins.json:common.world.MixinServerLevel,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin,pl:mixin:APP:biomemakeover-common.mixins.json:multipart.ServerLevelMixin,pl:mixin:APP:alternate-current.mixins.json:ServerLevelMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:blueprint.mixins.json:ServerLevelMixin,pl:mixin:APP:friendsandfoes-common.mixins.json:ServerWorldAccessor,pl:mixin:APP:friendsandfoes-common.mixins.json:ServerWorldMixin,pl:mixin:APP:rottencreatures-common.mixins.json:common.ServerLevelMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[server-1.19.2-20220805.130853-srg.jar%23323!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292) ~[server-1.19.2-20220805.130853-srg.jar%23323!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:nochatreports.mixins.json:server.MixinDedicatedServer,pl:mixin:APP:blueprint.mixins.json:DedicatedServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.19.2-20220805.130853-srg.jar%23323!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19.2-20220805.130853-srg.jar%23323!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23323!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}
```

**Comment by YeoXuHang** [comment]
What's the mod version?

**Comment by starlingfire** [comment]
geodeforge-1.1.5-1.19.2

**Comment by YeoXuHang** [comment]
Ok, will fix it in next update
