### ISSUE TITLE
Crash on load for forge 1.20.1

### ISSUE THREAD

**Issue by GwendiWendi** [YeoXuHang/Geode-Plus#73]
here is what seems to cause it but I will include the whole latest log and crash report below

Issue:
Caused by: java.lang.IllegalArgumentException: No model for layer geode_plus:wrappist_pedestal#main
	at net.minecraft.client.model.geom.EntityModelSet.m_171103_(EntityModelSet.java:17) ~[client-1.20.1-20230612.114412-srg.jar%231014!/:?]
	at net.minecraft.client.renderer.BlockEntityWithoutLevelRenderer.handler$big000$onResourceManagerReloadGeodePlus(BlockEntityWithoutLevelRenderer.java:564) ~[client-1.20.1-20230612.114412-srg.jar%231014!/:?]
	at net.minecraft.client.renderer.BlockEntityWithoutLevelRenderer.m_6213_(BlockEntityWithoutLevelRenderer.java:87) ~[client-1.20.1-20230612.114412-srg.jar%231014!/:?]
	at net.minecraft.server.packs.resources.ResourceManagerReloadListener.m_10759_(ResourceManagerReloadListener.java:15) ~[client-1.20.1-20230612.114412-srg.jar%231014!/:?]
	
	
	
	
	
	
	
	
	Latest Log:
	
[latest.log](https://github.com/YeoXuHang/Geode-Plus/files/13851630/latest.log)

	
	Crash Report:
	
[crash-2024-01-06_15.55.17-client.txt](https://github.com/YeoXuHang/Geode-Plus/files/13851635/crash-2024-01-06_15.55.17-client.txt)

	
	Debug Log:
	
[debug.log](https://github.com/YeoXuHang/Geode-Plus/files/13851634/debug.log)

**Comment by aking4125** [comment]
I think Geode plus is masking the real issue. Looking through your latest and debug logs. I saw this line here:

`[06Jan2024 15:55:00.705] [modloading-worker-0/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: missions, class com.kryeit.forge.MainImpl
java.lang.NoSuchMethodError: 'com.simibubi.create.foundation.data.CreateRegistrate com.simibubi.create.foundation.data.CreateRegistrate.useCreativeTab(net.minecraftforge.registries.RegistryObject)'
	at com.kryeit.entry.forge.ModCreativeTabsImpl.useBaseTab(ModCreativeTabsImpl.java:46) ~[missions-forge-0.2.4.jar%23837!/:?]`

Try updating Create Missions. 

I've gotten crashes like this before blaming Geode plus but it was some other issue.
